app:
  jwt:
    secret: d8e8fca2dc0f896fd778b9b0c1cba0e5f8a7c6d8b4e3c2a1f9e8d7c6b5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0
    expiration-ms: 86400000  # 24 hours
    refresh-expiration-ms: 2592000000  # 30 days

server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        hbm2ddl:
          auto: update
      javax.persistence.schema-generation.database.action: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
        web-admin-password: admin

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    co.com.pragma: DEBUG
